spring:
  application:
    name: octo-story-update-manager

  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 5672
  
  
  cloud:
    stream:
      bindings:
        UpdateStoryMessageSource:
          destination: updatestorymessage
    default:
      contentType: application/json
        


server:
  port: 9001
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
security:
  oauth2:
    resource:
      accessTokenUri: http://localhost:8090/auth/oauth/check_token
      userAuthorizationUri: http://localhost:8090/auth/oauth/authorize
      userInfoUri: http://localhost:8090/auth/user
      jwt:
        keyUri: http://localhost:8090/auth/oauth/token_key
